version: '3'
services:
    nginx:
        image: nginx:mainline-alpine
        container_name: webserver
        restart: always
        networks:
            - app-network
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        links:
            - php
#    certbot:
#        image: certbot/certbot
    php:
        build: ./images/php
        container_name: php
        restart: always
        networks:
            - app-network
        links:
            - mysql
        volumes:
            - ./www:/var/www

    mysql:
        image: mariadb
        container_name: php
        restart: always
        networks:
            - app-network
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
    pma:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        restart: always
        networks:
            - app-network
        links:
            - mysql:mysql
        ports:
            - 8183:80
        environment:
            PMA_HOST: mysql
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: secret
